### PR TITLE
Adding in github_documents in the vignettes

### PR DESCRIPTION
**Pull request by serbinsh**
... as yet another way to illustrate the scripts to end users

### CODE REVIEW

**Comment by neo0351** [comment]
I must have missed something.  What are these github docs?  I'm guessing it's like the pdf/html but on github?

**Comment by serbinsh** [comment]
@neo0351 I am covering all of the bases for how to present the code and what it does.  @JulienLamour reminded me that we can also provide markdown that will render on GitHub (hence github_document) so I updated the vignettes to include these as well. For example 

https://github.com/TESTgroup-BNL/PLSR_for_plant_trait_prediction/blob/github_docs/vignettes/spectra-trait_reseco_lma_plsr_example.md

**Comment by serbinsh** [comment]
So to me, we now have multiple ways that a user can interact and understand the scripts, plus the Zenodo archive, plus we will add the whole git repo as a zip file supplement to the paper, plus the workflow supplement to the paper so I can't see anything else we need to convey this to a user

**Comment by neo0351** [comment]
Makes sense

**Pull request merged**
