### PR TITLE
Updating script2

### PR DESCRIPTION
**Pull request by serbinsh**

### CODE REVIEW

**Comment by serbinsh** [comment]
@neo0351 quick review to just look for any red flags.  Nothing major changed just some clarity changes and small fixes.

**Comment by neo0351** [comment]
Ok, I'll have a look

**Review by neo0351 — APPROVED** [review]
I'm not following the "apply_sserbin2019_lma_plsr_to_neon_example".  It's different than the other examples, so why is it being added?  Is this just a "simple" example?

**Comment by serbinsh** [comment]
That is the first example of showing a previously fit model applied to new data. Its not exactly perfect but i dont have time to build one off the examples we have in here right now

**Comment by neo0351** [comment]
Oh!!!!  I see said the blind man.

**Pull request merged**
