### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by neo0351**
updated readme, small update of comment in function.R to reflect prior changes.

### CODE REVIEW

**Review by serbinsh — CHANGES_REQUESTED** [review]
@JulienLamour @neo0351 not sure the PLS component selection defs are correct

Isnt firstMin the first time the PRESS statistic of component # isnt significantly better in the following component (next highest).  Sorry that is the next component isnt significantly better?

And isn't first plateau where the remaining components to show any significantly better PRESS values?

**Comment by neo0351** [comment]
closing this request to fix the find_optimal_components issue

**Comment by serbinsh** [comment]
@neo0351 whats the issue?

**Comment by serbinsh** [comment]
you dont have to close the PR you just push new changes????

**Comment by neo0351** [comment]
Didn't know you could do that....

**Review by serbinsh — APPROVED** [review]

**Pull request merged**
